"""Where a biosignal comes from, and the two guards that make that answerable.

Why this module is the first thing in the package
-------------------------------------------------
The cognitive layer's whole risk is that a *simulated* signal is visually
indistinguishable from a *measured* one. A tachogram drawn from `random` looks
exactly like a tachogram drawn from a chest strap, and a ring that grows when a
number crosses a threshold looks exactly like neurofeedback whether or not
anybody is wearing anything. So provenance cannot be something a renderer
remembers to print. It has to be something a window cannot exist without.

Two guards, both in `__post_init__` or in a base class, neither in a comment:

* **A window cannot be constructed without a stamp that says SIMULATED.**
  `BiosignalWindow.__post_init__` raises otherwise. This is the same trick
  `src/dashboard/view.py::ScoreSurface` uses for `PROVISIONAL_STAMP` and
  `src/dashboard/bands.py::Band` uses for its caveat, and it is used here for
  the same reason: the render is the step most likely to be reimplemented, so
  the check must not live there.

* **A source cannot claim to be simulated without being a `SimulatedSource`.**
  `BiosignalSource` is a `Protocol`, and a runtime-checkable Protocol's
  `isinstance` only checks that attributes *exist* -- an object with
  `simulated = True` glued on passes it. That is precisely the "the check and
  the thing it protects were related by assumption" shape this repository has
  now found seven times. So the ethics gate in `require_simulated()` checks
  membership of a real abstract base class whose `simulated` property is not
  overridable to False, not the truthiness of an attribute.

# BLOCKED UNTIL ETHICS SIGN-OFF
------------------------------------------------------------------------------
Nothing in this package may touch a human being. `require_simulated()` refuses
any source that is not a `SimulatedSource`, and `dashboard/pages/` calls it
before rendering. Do not weaken it, comment it out, or add a "just for testing"
bypass.

The moment a real physiological signal from any person -- including the
repository owner's own -- reaches this code, `docs/ethics.md` and
`docs/model_card.md` must be updated FIRST, with a consent route, a retention
rule, and a statement that physiological data is a different privacy class from
synthetic text. V5 (closed-loop neurofeedback) is additionally an INTERVENTION
rather than an observation: a closed feedback loop changes the behaviour of the
person inside it, so it needs ethics approval and a clinician in the loop before
it runs against anyone. `MuseSource`, `OpenBCISource` and `PolarH10Source` are
named in `.claude.md` §11.3 as future drop-ins behind `BiosignalSource`; the
gate below is what stops one of them being wired up on a quiet afternoon.
"""

from __future__ import annotations

import math
import random
from abc import ABC, abstractmethod
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Protocol, runtime_checkable

#: The shortest trailing window the HF-HRV estimate is allowed to run on.
#:
#: Below about a dozen beats the high-frequency band spans a single DFT bin and
#: the estimate stops being an estimate -- observed as a load index pinned at
#: 0.00 for the opening seconds of every narrated clip. Twelve is not a clinical
#: minimum (those are quoted in minutes, not beats); it is the point at which
#: this simulator's number stops being nonsense, which is all the panel claims.
MIN_TRAILING_BEATS = 12

#: The token every stamp must contain. Checked as an uppercase substring rather
#: than as equality with `SIMULATED_STAMP`, so a source may extend the sentence
#: with its own parameters without being able to drop the word that matters.
SIMULATED_TOKEN = "SIMULATED"

#: The default stamp. Deliberately a full sentence rather than a label: a chip
#: reading "SIMULATED" alone gets cropped out of a screenshot and read as a
#: product name, which is the failure mode that a bare `0.71` labelled "risk"
#: already taught this project about.
SIMULATED_STAMP = (
    "SIMULATED SIGNAL: generated by this project's own simulator from a fixed seed. "
    "No person was recorded, no sensor was attached, and this window is not a "
    "measurement of anybody."
)


class EthicsGateError(RuntimeError):
    """Raised when a non-simulated source reaches a surface that forbids one.

    A distinct type rather than `ValueError` so nothing can catch it by accident
    while catching a construction error, and so `tests/test_biosignals.py` can
    assert the gate fires rather than assert that something merely failed.
    """


@dataclass(frozen=True)
class BiosignalWindow:
    """One slice of signal, inseparable from the statement of where it came from.

    `channels` carries raw traces (an EEG series, a run of RR intervals, a pupil
    trace) and `features` carries named scalars derived from them by the pure
    functions in `features.py`. A window computes nothing itself -- it is the
    carrier, in the same way `DashboardView` carries numbers it does not derive.

    `index` identifies the window within a source's stream, and is what makes a
    screenshot reproducible: `source.window(3)` is the same window on every run
    for a given seed, regardless of what was called before it.
    """

    source: str
    stamp: str
    index: int
    t0_s: float
    sample_rate_hz: float
    channels: Mapping[str, tuple[float, ...]] = field(default_factory=dict)
    features: Mapping[str, float] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if SIMULATED_TOKEN not in self.stamp.upper():
            raise ValueError(
                f"BiosignalWindow({self.source!r}) has no SIMULATED provenance stamp. "
                "A physiological trace with its provenance stripped off is "
                "indistinguishable from a measurement of a person; see this module's "
                "docstring and src/dashboard/view.py::ScoreSurface."
            )
        if not self.source.strip():
            raise ValueError("BiosignalWindow has no source name.")
        if self.sample_rate_hz <= 0:
            raise ValueError(f"sample_rate_hz must be positive, got {self.sample_rate_hz!r}.")
        if self.index < 0:
            raise ValueError(f"index must be non-negative, got {self.index!r}.")

        # Freeze the mappings. A frozen dataclass holding a plain dict is frozen
        # in name only -- the caller keeps a live reference and can rewrite the
        # numbers after every guard above has passed.
        channels = {}
        for name, samples in self.channels.items():
            if not name.strip():
                raise ValueError("a channel has an empty name.")
            values = tuple(float(s) for s in samples)
            if not values:
                raise ValueError(f"channel {name!r} is empty.")
            if any(not math.isfinite(v) for v in values):
                raise ValueError(f"channel {name!r} contains a non-finite sample.")
            channels[name] = values
        features = {}
        for name, value in self.features.items():
            if not name.strip():
                raise ValueError("a feature has an empty name.")
            number = float(value)
            if not math.isfinite(number):
                raise ValueError(f"feature {name!r} is not finite.")
            features[name] = number
        object.__setattr__(self, "channels", MappingProxyType(channels))
        object.__setattr__(self, "features", MappingProxyType(features))

    @property
    def duration_s(self) -> float:
        """Window length in seconds, from the longest channel. Derived, not stored."""
        if not self.channels:
            return 0.0
        return max(len(v) for v in self.channels.values()) / self.sample_rate_hz

    def context(self) -> dict[str, float]:
        """This window's features, shaped for `LinearRiskScorer.score(context=...)`.

        Names are prefixed so a biosignal feature can never collide with a
        construct name in the probabilities mapping. The scorer ignores this
        entirely unless `context_weights` were configured, and Phase 26 configures
        none -- see `.claude.md` §11.2 rule 2. The method exists so the *test*
        that the index is bit-identical with and without context has something
        real to pass in, rather than a hand-written dict that could drift away
        from what a page would actually supply.
        """
        return {f"biosignal_{name}": value for name, value in sorted(self.features.items())}


@dataclass(frozen=True)
class NarratedSession:
    """A whole clip's worth of simulated signal, plus the windows a player indexes.

    `narrate()` returns this rather than a bare tuple of windows because a panel
    synchronised to audio needs both halves and they must come from one
    generation pass. The full series is what gets DRAWN -- one continuous trace
    with a playhead moving along it -- and the windows are what gets READ OUT at
    the playhead. Returning only the windows meant the panel redrew a different
    ten-second slice every half second, so the trace jittered instead of the
    playhead moving. Returning only the series would leave the readouts with
    nothing to come from.

    `beat_times_s` can start negative: the lead-in described in `narrate()`.
    Anything before zero fills a trailing window and is never drawn.
    """

    windows: tuple[BiosignalWindow, ...]
    duration_s: float
    stamp: str
    beat_times_s: tuple[float, ...]
    rr_ms: tuple[float, ...]
    pupil_z: tuple[float, ...]
    blink: tuple[float, ...]
    pupil_rate_hz: float
    lead_s: float = 0.0

    def __post_init__(self) -> None:
        if SIMULATED_TOKEN not in self.stamp.upper():
            raise ValueError(
                "NarratedSession has no SIMULATED provenance stamp. A trace running "
                "under a voice is the most convincing artefact this project can "
                "produce; it does not get to exist without saying what it is."
            )
        if not self.windows:
            raise ValueError("a narrated session with no windows cannot be played.")

    @property
    def _lead_samples(self) -> int:
        return int(round(self.lead_s * self.pupil_rate_hz))

    @property
    def clip_pupil(self) -> tuple[float, ...]:
        """Pupil samples inside the clip. The lead-in fills windows, never a figure."""
        return self.pupil_z[self._lead_samples :]

    @property
    def clip_blink(self) -> tuple[float, ...]:
        return self.blink[self._lead_samples :]

    @property
    def clip_rr(self) -> tuple[tuple[float, float], ...]:
        """(time_s, rr_ms) for beats inside the clip. Excludes the lead-in."""
        return tuple(
            (t, rr) for t, rr in zip(self.beat_times_s, self.rr_ms, strict=True) if t >= 0.0
        )


@runtime_checkable
class BiosignalSource(Protocol):
    """What a page is allowed to ask a signal source for.

    Mirrors `src/dashboard/backend.py::PredictionBackend`: a narrow surface, so a
    real device drops in behind it later with no page change.

    This Protocol is for typing and for documenting the seam. It is NOT the
    ethics gate -- `isinstance` against a runtime-checkable Protocol checks only
    that the attribute names exist, so any object with `simulated = True` on it
    satisfies this. Use `require_simulated()` for the gate.
    """

    name: str
    stamp: str
    simulated: bool

    def window(self, index: int) -> BiosignalWindow:  # pragma: no cover - Protocol
        ...


class SimulatedSource(ABC):
    """Base class for every source that generates rather than measures.

    Being a simulated source is membership of this class, not the value of a
    flag. `simulated` is a property with no setter and it returns a literal, so a
    subclass that wants to lie has to visibly override a property rather than
    quietly assign an attribute -- and `require_simulated()` checks the class, not
    the property, so even that would not get past the gate.

    Subclasses generate from `seed` and `index` only. No instance state
    accumulates between calls, which is what makes `window(3)` return the same
    window whether it is the first call or the thousandth -- the property a
    reproducible screenshot depends on, and one that a `self._rng` advanced in
    place would quietly break.
    """

    def __init__(self, *, name: str, seed: int, stamp: str = SIMULATED_STAMP) -> None:
        if not name.strip():
            raise ValueError("a source must have a name.")
        if SIMULATED_TOKEN not in stamp.upper():
            raise ValueError(
                f"SimulatedSource({name!r}) was given a stamp that does not say "
                f"{SIMULATED_TOKEN!r}. Every window this source emits carries this "
                "string; a source that can be constructed without it can emit a trace "
                "that reads as a measurement."
            )
        self.name = name
        self.seed = int(seed)
        self.stamp = stamp

    @property
    def simulated(self) -> bool:
        """Always True. See the class docstring for why this is not a field."""
        return True

    def rng(self, index: int) -> random.Random:
        """A generator determined by (seed, index) and nothing else.

        Seeded from a string rather than a tuple: `random.Random` accepts only
        None, int, float, str, bytes and bytearray, and a tuple raises. String
        seeding is deterministic across runs and across machines (CPython hashes
        the bytes with SHA-512 for this purpose rather than using the
        salted `hash()`), which is the property a reproducible figure needs.
        """
        return random.Random(f"{self.name}:{self.seed}:{int(index)}")

    @abstractmethod
    def window(self, index: int) -> BiosignalWindow:
        """The window at position `index` in this source's stream."""

    def stream(self, count: int, *, start: int = 0) -> tuple[BiosignalWindow, ...]:
        """`count` consecutive windows. Pure: calling it twice returns equals."""
        if count < 0:
            raise ValueError("count must be non-negative.")
        return tuple(self.window(start + i) for i in range(count))


def require_simulated(source: object) -> SimulatedSource:
    """The ethics gate. Returns the source, or refuses to let the caller proceed.

    # BLOCKED UNTIL ETHICS SIGN-OFF -- see this module's docstring.

    Called by every page in `dashboard/pages/` that renders a biosignal, before
    anything is drawn. It returns the source rather than returning a bool so the
    call cannot be written and then have its result ignored: the only way to get
    a usable source out of it is to pass the gate.
    """
    if not isinstance(source, SimulatedSource):
        raise EthicsGateError(
            f"{type(source).__name__} is not a SimulatedSource, so it is refused. "
            "Nothing in Phase 26 may touch a human being. Before any real "
            "physiological signal from any person -- including the repository "
            "owner's own -- reaches this code, docs/ethics.md and docs/model_card.md "
            "must be updated first with a consent route, a retention rule, and a "
            "statement that physiological data is a different privacy class from "
            "synthetic text. A closed feedback loop (V5) additionally needs ethics "
            "approval and a clinician in the loop, because it is an intervention "
            "rather than an observation."
        )
    return source


class SimulatedEEGSource(SimulatedSource):
    """A synthetic EEG-shaped series with a slowly wandering alpha/theta balance.

    What this is and is not
    -----------------------
    It is a sum of two sinusoids and noise. It is not a model of cortical
    activity, it is not fitted to any recording, and its numbers mean nothing
    outside this simulator. It exists so the V5 ring has something to respond to
    that behaves the way a real ratio behaves -- drifting on a timescale of tens
    of seconds, crossing a threshold and coming back -- rather than a random walk
    that never settles or a sine that is obviously a sine.

    The construction, stated so a reviewer can check it rather than trust it:

        sample(t) = alpha_amp(index) * cos(2*pi*ALPHA_HZ*t + phase_a)
                  + THETA_AMP       * cos(2*pi*THETA_HZ*t + phase_t)
                  + gauss(0, NOISE_SD)

        alpha_amp(index) = ALPHA_BASE + ALPHA_SWING * sin(2*pi*index/DRIFT_PERIOD)

    `alpha_amp` is the only thing that moves between windows, so the alpha/theta
    ratio rises and falls on a `DRIFT_PERIOD`-window cycle. Phases are drawn per
    window so consecutive windows are not phase-continuous -- which is honest:
    this is a bag of independent windows, not a continuous recording, and
    pretending otherwise would be the first step towards treating it as one.
    """

    #: Band centres. Inside the conventional theta (4-8 Hz) and alpha (8-13 Hz)
    #: ranges used by `features.THETA_BAND` / `features.ALPHA_BAND`, and placed
    #: on exact DFT bin centres for the default window so the hand-computed test
    #: fixtures in `tests/test_biosignals.py` are exact rather than approximate.
    ALPHA_HZ = 10.0
    THETA_HZ = 6.0

    ALPHA_BASE = 1.0
    ALPHA_SWING = 0.55
    THETA_AMP = 1.0
    NOISE_SD = 0.12
    DRIFT_PERIOD = 24  # windows per full rise-and-fall cycle

    def __init__(
        self,
        *,
        seed: int = 20260913,
        sample_rate_hz: float = 128.0,
        samples: int = 256,
        name: str = "simulated-eeg",
        stamp: str = SIMULATED_STAMP,
    ) -> None:
        super().__init__(name=name, seed=seed, stamp=stamp)
        if samples < 2:
            raise ValueError("a window needs at least two samples.")
        if sample_rate_hz <= 0:
            raise ValueError("sample_rate_hz must be positive.")
        self.sample_rate_hz = float(sample_rate_hz)
        self.samples = int(samples)

    def alpha_amplitude(self, index: int) -> float:
        """The alpha amplitude for one window. Public so a test can predict it."""
        return self.ALPHA_BASE + self.ALPHA_SWING * math.sin(
            2.0 * math.pi * (index % self.DRIFT_PERIOD) / self.DRIFT_PERIOD
        )

    def window(self, index: int) -> BiosignalWindow:
        from src.biosignals.features import (
            ALPHA_BAND,
            THETA_BAND,
            alpha_theta_ratio,
            band_power,
        )

        rng = self.rng(index)
        phase_a = rng.uniform(0.0, 2.0 * math.pi)
        phase_t = rng.uniform(0.0, 2.0 * math.pi)
        alpha_amp = self.alpha_amplitude(index)
        dt = 1.0 / self.sample_rate_hz

        series = tuple(
            alpha_amp * math.cos(2.0 * math.pi * self.ALPHA_HZ * (n * dt) + phase_a)
            + self.THETA_AMP * math.cos(2.0 * math.pi * self.THETA_HZ * (n * dt) + phase_t)
            + rng.gauss(0.0, self.NOISE_SD)
            for n in range(self.samples)
        )

        alpha = band_power(series, self.sample_rate_hz, *ALPHA_BAND)
        theta = band_power(series, self.sample_rate_hz, *THETA_BAND)
        return BiosignalWindow(
            source=self.name,
            stamp=self.stamp,
            index=index,
            t0_s=index * self.samples / self.sample_rate_hz,
            sample_rate_hz=self.sample_rate_hz,
            channels={"eeg": series},
            features={
                "alpha_power": alpha,
                "theta_power": theta,
                "alpha_theta_ratio": alpha_theta_ratio(alpha, theta),
            },
        )


class SimulatedCardioOculoSource(SimulatedSource):
    """A synthetic chest-strap and webcam pair driven by one arousal drift.

    What this is and is not
    -----------------------
    It is arithmetic. There is no heart, no eye, no camera and no person. It
    exists so `load_panel` has something to draw that behaves the way the real
    channels behave -- a slow arousal drift that RR, pupil and blink all respond
    to, rather than three independent random walks that never tell a story.

    The construction, stated so a reviewer can check it rather than trust it.
    One latent value drives all three channels:

        arousal(index) = 0.5 + 0.5 * sin(2*pi*index / DRIFT_PERIOD)

        RR(n)    = (RR_BASE - RR_AROUSAL_MS * arousal)
                   + RSA_MS * (1 - 0.7*arousal) * sin(2*pi*n / RSA_BEATS)
                   + gauss(0, RR_NOISE_MS)
        pupil(n) = PUPIL_BASE_Z + PUPIL_AROUSAL_Z * arousal + gauss(0, PUPIL_NOISE_Z)
        blink    ~ Bernoulli per sample at (BLINK_BASE - BLINK_AROUSAL * arousal)/min

    The respiratory term shrinks as arousal rises, which is what makes HF-HRV
    fall while pupil rises -- the correlation the panel is showing. It is
    imposed here by construction; it is not a finding, and nothing in this
    repository measured it.

    Blink rate falls with arousal in this simulator while `features.LOAD_WEIGHTS`
    gives blink rate a POSITIVE weight. That disagreement is deliberate and left
    in: the two were written from different assumptions, which is exactly the
    situation a real recording would put the project in, and a simulator tuned
    to agree with its own index would make the panel untestable.
    """

    RR_BASE_MS = 900.0
    RR_AROUSAL_MS = 220.0
    RR_NOISE_MS = 9.0
    RSA_MS = 34.0
    RSA_BEATS = 4.2  # beats per respiratory cycle, so the HF band is populated

    PUPIL_BASE_Z = -0.55
    PUPIL_AROUSAL_Z = 1.9
    PUPIL_NOISE_Z = 0.16

    BLINK_BASE_PER_MIN = 19.0
    BLINK_AROUSAL_PER_MIN = 8.0

    DRIFT_PERIOD = 16  # windows per full rise-and-fall cycle

    def __init__(
        self,
        *,
        seed: int = 20260913,
        window_s: float = 60.0,
        pupil_rate_hz: float = 10.0,
        name: str = "simulated-cardio-oculo",
        stamp: str = SIMULATED_STAMP,
    ) -> None:
        super().__init__(name=name, seed=seed, stamp=stamp)
        if window_s <= 0 or pupil_rate_hz <= 0:
            raise ValueError("window_s and pupil_rate_hz must be positive.")
        self.window_s = float(window_s)
        self.pupil_rate_hz = float(pupil_rate_hz)

    def arousal(self, index: int) -> float:
        """The latent drift, in [0, 1]. Public so a test can predict it."""
        return 0.5 + 0.5 * math.sin(2.0 * math.pi * (index % self.DRIFT_PERIOD) / self.DRIFT_PERIOD)

    def window(self, index: int) -> BiosignalWindow:
        from src.biosignals.features import blink_rate, hf_hrv, load_index, pupil_effort

        rng = self.rng(index)
        a = self.arousal(index)

        mean_rr = self.RR_BASE_MS - self.RR_AROUSAL_MS * a
        beats = max(4, int(round(self.window_s * 1000.0 / mean_rr)))
        rsa = self.RSA_MS * (1.0 - 0.7 * a)
        rr = tuple(
            mean_rr
            + rsa * math.sin(2.0 * math.pi * n / self.RSA_BEATS)
            + rng.gauss(0.0, self.RR_NOISE_MS)
            for n in range(beats)
        )

        samples = max(2, int(round(self.window_s * self.pupil_rate_hz)))
        pupil = tuple(
            self.PUPIL_BASE_Z + self.PUPIL_AROUSAL_Z * a + rng.gauss(0.0, self.PUPIL_NOISE_Z)
            for _ in range(samples)
        )

        per_min = self.BLINK_BASE_PER_MIN - self.BLINK_AROUSAL_PER_MIN * a
        p_sample = (per_min / 60.0) / self.pupil_rate_hz
        blinks = tuple(1.0 if rng.random() < p_sample else 0.0 for _ in range(samples))

        hf = hf_hrv(rr)
        effort = pupil_effort(pupil)
        rate = blink_rate(blinks, self.window_s)
        return BiosignalWindow(
            source=self.name,
            stamp=self.stamp,
            index=index,
            t0_s=index * self.window_s,
            sample_rate_hz=self.pupil_rate_hz,
            channels={"rr_ms": rr, "pupil_z": pupil, "blink": blinks},
            features={
                "hf_hrv": hf,
                "pupil_effort": effort,
                "blink_rate": rate,
                "load_index": load_index(hf, effort, rate),
            },
        )

    def narrate(
        self,
        arousal_track: Sequence[float],
        duration_s: float,
        *,
        step_s: float = 0.5,
        trailing_s: float = 10.0,
    ) -> NarratedSession:
        """A continuous session driven by an arousal track, as trailing windows.

        `window()` above chops the simulation into independent blocks, which is
        right for a source with nothing to synchronise to. This is for the case
        where there IS something: a clip of speech playing, with the physiology
        expected to respond to it as it plays.

        So one continuous session is generated first -- beats laid end to end,
        pupil and blinks sampled across the whole clip -- and then sliced into
        overlapping windows ending every `step_s` seconds, each carrying the
        preceding `trailing_s` of signal. A player maps the audio's current time
        onto an index and gets the features as they stood at that moment.

        `t0_s` on each window is the time the window ENDS, i.e. the playhead
        position it belongs to, because that is the only time a caller ever wants
        to match against an audio element. Windows before the first full trailing
        period are short rather than absent: dropping them would make the panel
        start ten seconds into an eight-second clip.

        The arousal track is imposed from outside -- see
        `features.arousal_curve` and the long comment above it. Nothing here
        observes anything.
        """
        from src.biosignals.features import (
            blink_rate,
            heart_rate_bpm,
            pupil_effort,
            short_window_load_index,
        )

        track = [max(0.0, min(1.0, float(a))) for a in arousal_track]
        if len(track) < 2:
            raise ValueError("an arousal track needs at least two samples.")
        if duration_s <= 0 or step_s <= 0 or trailing_s <= 0:
            raise ValueError("duration_s, step_s and trailing_s must be positive.")

        def arousal_at(t: float) -> float:
            """Linear interpolation into the track. No extrapolation past the end."""
            pos = max(0.0, min(1.0, t / duration_s)) * (len(track) - 1)
            low = int(pos)
            high = min(low + 1, len(track) - 1)
            return track[low] + (track[high] - track[low]) * (pos - low)

        rng = self.rng(0)

        # A lead-in of `trailing_s` seconds BEFORE the clip starts, at floor
        # arousal, with negative timestamps.
        #
        # Without it the first windows hold two or three beats, and HF power over
        # three beats is one DFT bin -- which came out as a load index of 0.00 for
        # the first third of every clip. The fix is not to special-case the early
        # windows but to give them something real to look at: the simulated body
        # existed before the recording started, the same way a real one would
        # have. Nothing in the lead-in is ever drawn; it only fills the window.
        beat_times: list[float] = []
        rr_series: list[float] = []
        t = -float(trailing_s)
        n = 0
        while t < duration_s:
            a = arousal_at(t)
            rr = (
                self.RR_BASE_MS
                - self.RR_AROUSAL_MS * a
                + self.RSA_MS * (1.0 - 0.7 * a) * math.sin(2.0 * math.pi * n / self.RSA_BEATS)
                + rng.gauss(0.0, self.RR_NOISE_MS)
            )
            rr = max(300.0, rr)
            beat_times.append(t)
            rr_series.append(rr)
            t += rr / 1000.0
            n += 1

        # Pupil and blinks get the same lead-in as the beats, for the same
        # reason: without it the first window held two pupil samples, and a mean
        # over two samples put the load index at 0.82 before settling to 0.64 --
        # an opening spike that looked like the athlete reacting to the first
        # word and was pure small-sample noise. Sample i is at
        # t = -trailing_s + i / pupil_rate_hz.
        lead_s = float(trailing_s)
        samples = max(2, int(round((duration_s + lead_s) * self.pupil_rate_hz)))
        pupil_series = []
        blink_series = []
        for i in range(samples):
            a = arousal_at(i / self.pupil_rate_hz - lead_s)
            pupil_series.append(
                self.PUPIL_BASE_Z + self.PUPIL_AROUSAL_Z * a + rng.gauss(0.0, self.PUPIL_NOISE_Z)
            )
            per_min = self.BLINK_BASE_PER_MIN - self.BLINK_AROUSAL_PER_MIN * a
            p_sample = (per_min / 60.0) / self.pupil_rate_hz
            blink_series.append(1.0 if rng.random() < p_sample else 0.0)

        windows: list[BiosignalWindow] = []
        steps = int(duration_s / step_s) + 1
        for index in range(steps):
            end = min(duration_s, index * step_s)
            start = end - trailing_s
            rr = [r for bt, r in zip(beat_times, rr_series, strict=True) if start <= bt <= end]
            if len(rr) < MIN_TRAILING_BEATS:
                # Reach further back, never forward: a playhead may not show a
                # number computed from beats that have not been heard yet.
                past = [r for bt, r in zip(beat_times, rr_series, strict=True) if bt <= end]
                rr = past[-MIN_TRAILING_BEATS:] or past
            lo = max(0, int((start + lead_s) * self.pupil_rate_hz))
            hi = max(lo + 2, int((end + lead_s) * self.pupil_rate_hz))
            pupil = pupil_series[lo:hi] or pupil_series[:2]
            blinks = blink_series[lo:hi] or blink_series[:2]
            span = max(0.5, (hi - lo) / self.pupil_rate_hz)

            effort = pupil_effort(pupil)
            rate = blink_rate(blinks, span)
            windows.append(
                BiosignalWindow(
                    source=self.name,
                    stamp=self.stamp,
                    index=index,
                    t0_s=end,
                    sample_rate_hz=self.pupil_rate_hz,
                    channels={
                        "rr_ms": tuple(rr),
                        "pupil_z": tuple(pupil),
                        "blink": tuple(blinks),
                    },
                    features={
                        "pupil_effort": effort,
                        "blink_rate": rate,
                        # Two channels, not three. See SHORT_LOAD_WEIGHTS for why
                        # no HRV statistic appears on a window this short.
                        "load_index": short_window_load_index(effort, rate),
                        # The beat-to-beat number, from the last few beats only,
                        # so it responds within a second of a phrase being said.
                        "heart_rate_bpm": heart_rate_bpm(rr[-6:] or rr),
                        "arousal": arousal_at(end),
                    },
                )
            )
        return NarratedSession(
            windows=tuple(windows),
            duration_s=float(duration_s),
            stamp=self.stamp,
            beat_times_s=tuple(beat_times),
            rr_ms=tuple(rr_series),
            pupil_z=tuple(pupil_series),
            blink=tuple(blink_series),
            pupil_rate_hz=self.pupil_rate_hz,
            lead_s=lead_s,
        )


def as_series(samples: Sequence[float]) -> tuple[float, ...]:
    """Small helper so callers stop passing lists into frozen structures."""
    return tuple(float(s) for s in samples)
