"""Emit the Phase 20 paper figure from the committed known examples.

The figure is generated by the *same* code the dashboard renders with, from the
*same* fixture the gate reproduces. That is deliberate and it is the point of
C2.6: if the paper figure had its own drawing code, the demo and the figure
would drift apart and one of them would eventually be wrong without anyone
noticing which.

`PROJECT_PLAN.md` Phase 24 gates on "figures legible in grayscale", so this
script also writes a desaturated proof next to the figure. A marking that leans
on hue passes review on a colour screen and fails in print -- after the figure
has been drawn and the caption written.

Run:  python scripts/build_dashboard_figure.py
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.dashboard import (  # noqa: E402
    build_view,
    construct_contribution_chart,
    known_examples,
    risk_meter,
)

OUT = REPO_ROOT / "reports" / "figures"
#: The clearest positive case: one dominant construct with real supporting spans,
#: five drivers with none, and four inert constructs on the same axis. A figure
#: showing only the part that worked would be a worse figure.
FIGURE_EXAMPLE = "synth_precomp_v1-003481"

CAPTION = (
    "Two-level explanation for one synthetic record. Sign is encoded by position "
    "relative to the rule, not by colour; the four directionally unresolved "
    "constructs carry a hatched, dashed marker and an explicit (inert) label. "
    "PROVISIONAL - planted-label corpus-property measurement, NOT accuracy. "
    "data/gold/ is empty (OPEN-025); no real athlete text exists (OPEN-011)."
)


def main() -> int:
    backend = known_examples()
    view = build_view(example_id=FIGURE_EXAMPLE, backend=backend)
    OUT.mkdir(parents=True, exist_ok=True)

    width = 760
    meter = risk_meter(view.risk, width=width)
    chart = construct_contribution_chart(view.bars, width=width)
    meter_h, chart_h = 96, len(view.bars) * 26 + 56
    caption_h = 13 * len(textwrap.wrap(CAPTION, width=112)) + 22
    height = meter_h + chart_h + caption_h

    # Composed as *nested* <svg> elements with x/y offsets rather than by slicing
    # the children's markup into <g> wrappers. The slicing version rendered a
    # blank figure -- each child's own </svg> closed the parent early -- and the
    # only reason that was caught is that this script writes a proof image and
    # someone looked at it. Two defects in this phase have now been found by
    # looking rather than by asserting.
    def _nested(markup: str, y_offset: int) -> str:
        return markup.replace("<svg ", f'<svg x="0" y="{y_offset}" ', 1)

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">',
        f'<rect width="{width}" height="{height}" fill="#fcfcfb"/>',
        _nested(meter, 0),
        _nested(chart, meter_h),
    ]
    y = meter_h + chart_h + 16
    # Wrapped on word boundaries. The naive fixed-width slice split "(inert)"
    # across two lines and truncated "(OPEN-025)" to "(OPE" -- in a caption whose
    # whole job is to carry the provenance caveat intact.
    for i, part in enumerate(textwrap.wrap(CAPTION, width=112)):
        lines.append(
            f'<text x="8" y="{y + i * 13}" font-family="system-ui, sans-serif" '
            f'font-size="9" fill="#52514e">{part}</text>'
        )
    lines.append("</svg>")

    path = OUT / "phase20_explanation_card.svg"
    path.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
