"""Match-day scenarios: pressure/life-context combinations for synthetic demo text.

Why this exists
----------------
The Match-day profile page (`dashboard/pages/6_Match_day_profile.py`) scores a
real press conference only when `SRN_MATCHDAY_REAL_ATHLETES` is set -- declined
by owner decision, `docs/phase29_decision_draft.md`, 2026-09-20. This module
gives that page something honest to score in the meantime: a scenario the
reader picks from dropdowns, generated by the same seeded template grammar
that produced every `synth_precomp_v1-*` example (`src/ingestion/synthetic.py`)
-- reproducible, zero-cost, no LLM, no real athlete.

Reuse, not modification
------------------------
`synthetic.py`'s own version history is explicit that changing its
construct-drawing or realisation logic reshuffles the RNG stream for every
existing corpus artefact seeded against it. This module therefore imports the
realisation banks and the framing/variation helpers UNCHANGED and adds exactly
one new mechanism: a `life_context -> construct bias` table that decides which
constructs a scenario plants and at what intensity or label, so two different
dropdown combinations produce a visibly different construct set -- not just a
different label on the same generic text. `synthetic.py` itself is untouched;
`generate_records` and every seed-42 fixture built against it are unaffected.

Grounding for the bias table
-----------------------------
Every construct named below cites the same `config/taxonomy.yaml` instrument
anchor that construct already carries in `synthetic.py`'s own realisation
bank, so this table is "grounded in the same instruments," not invented fresh
for this feature.

Why "timing," not "during or after the event"
-----------------------------------------------
`synthetic.py`'s docstring records that the Phase 7 source survey deliberately
excluded post-match text: it expresses relief, disappointment and attribution
-- constructs outside this project's taxonomy. Offering a "during" or "after"
option here would either need new taxonomy work or silently generate text the
taxonomy cannot score meaningfully. `TIMINGS` therefore stays entirely on the
pre-competition side, varying only the distance from the event.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

from .records import RawRecord
from .synthetic import (
    CATEGORICAL_REALISATIONS,
    GENERATOR_NAME,
    GENERATOR_VERSION,
    GRADED_REALISATIONS,
    INTERPRETATION_REALISATIONS,
    NEUTRAL_SENTENCES,
    SPORTS,
    _contradicts,
    _draw_constructs,
    _fill,
    _frame,
    _realise,
    _vary,
)

__all__ = [
    "LIFE_CONTEXT_LABELS",
    "LIFE_CONTEXTS",
    "SPORTS",
    "TIMING_LABELS",
    "TIMINGS",
    "MatchDayScenario",
    "generate_scenario_record",
]

TIMINGS: tuple[str, ...] = ("week_before", "morning_of", "immediately_before")

TIMING_LABELS: dict[str, str] = {
    "week_before": "A week before",
    "morning_of": "The morning of",
    "immediately_before": "Immediately before competing",
}

#: Representative time_to_competition_days per timing -- honest about what this
#: project can score: distances BEFORE the competition, never after (see
#: module docstring).
_TIMING_DAYS: dict[str, int] = {
    "week_before": 7,
    "morning_of": 0,
    "immediately_before": 0,
}

LIFE_CONTEXTS: tuple[str, ...] = (
    "none",
    "injury_comeback",
    "recent_loss",
    "strong_season",
    "personal_disruption",
)

LIFE_CONTEXT_LABELS: dict[str, str] = {
    "none": "No particular context",
    "injury_comeback": "Coming back from injury",
    "recent_loss": "Coming off a loss",
    "strong_season": "Coming off a strong season",
    "personal_disruption": "A difficult personal patch (e.g. a breakup, a bereavement)",
}


@dataclass(frozen=True)
class MatchDayScenario:
    """The three dropdown choices, together and validated."""

    sport: str
    timing: str
    life_context: str

    def __post_init__(self) -> None:
        if self.sport not in SPORTS:
            raise ValueError(f"unknown sport {self.sport!r}; must be one of {SPORTS}")
        if self.timing not in TIMINGS:
            raise ValueError(f"unknown timing {self.timing!r}; must be one of {TIMINGS}")
        if self.life_context not in LIFE_CONTEXTS:
            raise ValueError(
                f"unknown life_context {self.life_context!r}; must be one of {LIFE_CONTEXTS}"
            )


@dataclass(frozen=True)
class _Directive:
    """One construct a life_context plants, and how strongly."""

    construct: str
    intensity_band: tuple[int, int] | None = None  # graded constructs: (lo, hi)
    label: str | None = None  # categorical constructs: the label to favour
    label_weight: float = 0.7  # chance of the named label vs. a random other one


#: The actual bias mechanism. "none" is deliberately empty: it falls back to
#: `synthetic._draw_constructs`'s ordinary unbiased draw, so the baseline
#: scenario reads exactly like a generic corpus record rather than like a
#: fifth, invented context.
SCENARIO_BIAS: dict[str, tuple[_Directive, ...]] = {
    "none": (),
    "injury_comeback": (
        # CSAI-2 cognitive-anxiety subscale [Martens1990; Cox2003]
        _Directive("cognitive_anxiety", intensity_band=(2, 3)),
        # Theory of Challenge and Threat States in Athletes [JonesMeijen2009]
        _Directive("appraisal_orientation", label="threat", label_weight=0.7),
        # CD-RISC resilience construct [Connor2003]; resilience as mediator [Li2025]
        _Directive("resilience", intensity_band=(2, 3)),
    ),
    "recent_loss": (
        # CSAI-2 cognitive-anxiety subscale [Martens1990; Cox2003]
        _Directive("cognitive_anxiety", intensity_band=(1, 2)),
        # Theory of Challenge and Threat States in Athletes [JonesMeijen2009]
        _Directive("appraisal_orientation", label="threat", label_weight=0.65),
        # Coping in sport systematic review [Nicholls2007]
        _Directive("coping_style", label="avoidance", label_weight=0.6),
    ),
    "strong_season": (
        # CSAI-2 self-confidence subscale [Martens1990; Cox2003]
        _Directive("self_confidence", intensity_band=(2, 3)),
        # 2x2 achievement-goal framework [Elliot2001]; SDT [Deci2000]
        _Directive("motivation_orientation", label="approach", label_weight=0.75),
        # Theory of Challenge and Threat States in Athletes [JonesMeijen2009]
        _Directive("appraisal_orientation", label="challenge", label_weight=0.7),
    ),
    "personal_disruption": (
        # Perceived Stress Scale [Cohen1983]; pre-competition stress [Toth2025]
        _Directive("perceived_stress", intensity_band=(2, 3)),
        # Athlete Burnout Questionnaire [Raedeke2001]
        _Directive("burnout_signal", intensity_band=(1, 2)),
        # Attentional width/direction model and TAIS [Nideffer1976]
        _Directive("attentional_focus", label="distracted", label_weight=0.6),
    ),
}


def _realise_graded_at(construct: str, rng: random.Random, sport: str, band: tuple[int, int]):
    lo, hi = band
    intensity = rng.randint(lo, hi)
    bank = GRADED_REALISATIONS[construct][intensity]
    index = rng.randrange(len(bank))
    spec = {
        "construct": construct,
        "intensity": intensity,
        "template_id": f"{construct}:i{intensity}:{index}",
    }
    return _fill(bank[index], sport), spec


def _realise_categorical_at(
    construct: str, rng: random.Random, sport: str, label: str, label_weight: float
):
    labels = CATEGORICAL_REALISATIONS[construct]
    others = [name for name in labels if name != label]
    chosen = label if (not others or rng.random() < label_weight) else rng.choice(others)
    bank = labels[chosen]
    index = rng.randrange(len(bank))
    spec = {
        "construct": construct,
        "label": chosen,
        "template_id": f"{construct}:{chosen}:{index}",
    }
    return _fill(bank[index], sport), spec


def generate_scenario_record(
    scenario: MatchDayScenario, *, seed: int, source_id: str = "matchday_scenario_v1"
) -> RawRecord:
    """One synthetic record shaped by `scenario`, deterministic in `seed`.

    Same scenario + same seed -> byte-identical text, exactly like
    `synthetic.generate_records`'s own determinism guarantee. A different
    `life_context` at the same sport/timing plants a different construct set
    (`SCENARIO_BIAS`), which is what makes two dropdown choices score
    differently rather than merely read differently.
    """
    rng = random.Random(seed)
    sentences: list[str] = []
    planted: list[dict] = []

    if rng.random() < 0.35:
        sentences.append(_vary(_fill(rng.choice(NEUTRAL_SENTENCES), scenario.sport), rng))

    directives = SCENARIO_BIAS[scenario.life_context]
    if directives:
        for directive in directives:
            if directive.intensity_band is not None:
                sentence, spec = _realise_graded_at(
                    directive.construct, rng, scenario.sport, directive.intensity_band
                )
            else:
                sentence, spec = _realise_categorical_at(
                    directive.construct,
                    rng,
                    scenario.sport,
                    directive.label,
                    directive.label_weight,
                )
            sentences.append(_vary(_frame(sentence, rng), rng))
            planted.append(spec)
    else:
        # "none": the ordinary unbiased draw, so the baseline scenario reads
        # like a generic corpus record rather than a fifth invented context.
        for construct in _draw_constructs(rng):
            sentence, spec = _realise(construct, rng, scenario.sport)
            if _contradicts(spec, planted):
                sentence, spec = _realise(construct, rng, scenario.sport, cap_intensity=2)
            sentences.append(_vary(_frame(sentence, rng), rng))
            planted.append(spec)

    anxiety = [
        p
        for p in planted
        if p["construct"] in ("cognitive_anxiety", "somatic_anxiety") and p.get("intensity", 0) >= 2
    ]
    interpretation: str | None = None
    if anxiety and rng.random() < 0.45:
        appraisal = next(
            (p.get("label") for p in planted if p["construct"] == "appraisal_orientation"), None
        )
        if appraisal == "challenge":
            interpretation = "facilitative"
        elif appraisal == "threat":
            interpretation = "debilitative"
        else:
            interpretation = rng.choice(("facilitative", "debilitative"))
        sentences.append(
            _vary(
                _fill(rng.choice(INTERPRETATION_REALISATIONS[interpretation]), scenario.sport), rng
            )
        )

    if not sentences:
        sentences.append(_vary(_fill(rng.choice(NEUTRAL_SENTENCES), scenario.sport), rng))

    return RawRecord(
        record_id=(
            f"{source_id}-{scenario.sport}-{scenario.timing}-{scenario.life_context}-{seed:06d}"
        ),
        source_id=source_id,
        text=" ".join(sentences),
        time_to_competition_days=_TIMING_DAYS[scenario.timing],
        sport=scenario.sport,
        competition_level=None,
        region=None,
        source_type="synthetic",
        language="en",
        training_load_hint=None,
        synthetic=True,
        deidentified=False,
        generation_spec={
            "planted_constructs": planted,
            "interpretation_modifier": interpretation,
            "scenario": {
                "sport": scenario.sport,
                "timing": scenario.timing,
                "life_context": scenario.life_context,
            },
            "generator": f"{GENERATOR_NAME}@{GENERATOR_VERSION}+scenario",
            "seed": seed,
            "NOTE": (
                "Generation metadata, NOT a label. Never use as evaluation ground truth "
                "-- see docs/data_sources.md."
            ),
        },
    )
